name: C/C++ CI

on:
  push:
    branches: [ openwrt-18.06 ]
  pull_request:
    branches: [ openwrt-18.06 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: ./scripts/feeds update -a
    - name: install
      run: ./scripts/feeds install -a
    - name: makeMenu
      run: make menuconfig
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
